/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package System;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zvlmr
 */
public class Product extends javax.swing.JFrame {
public static class ProductItem {
        String name;
        int quantity;

        public ProductItem(String name, int quantity) {
            this.name = name;
            this.quantity = quantity;
        }
    }

    // List to hold products (static so accessible by Dashboard)
    public static ArrayList<ProductItem> productList = new ArrayList<>();
    /**
     * Creates new form Product
     */
    public Product() {
        initComponents();
    }
private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JLabel lblName = new JLabel("Product Name:");
        JLabel lblQuantity = new JLabel("Quantity:");
        JTextField txtName = new JTextField(20);
        JTextField txtQuantity = new JTextField(5);
        JButton btnAdd = new JButton("Add Product");
        JTextArea taProducts = new JTextArea(10, 30);
        taProducts.setEditable(false);

        JScrollPane scrollPane = new JScrollPane(taProducts);

        btnAdd.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                String name = txtName.getText().trim();
                String qtyStr = txtQuantity.getText().trim();
                if(name.isEmpty() || qtyStr.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please enter product name and quantity.");
                    return;
                }
                try {
                    int qty = Integer.parseInt(qtyStr);
                    if(qty < 0) {
                        JOptionPane.showMessageDialog(null, "Quantity cannot be negative.");
                        return;
                    }
                    // Add product to list
                    productList.add(new ProductItem(name, qty));
                    // Update textarea display
                    updateProductDisplay(taProducts);
                    // Clear inputs
                    txtName.setText("");
                    txtQuantity.setText("");
                    // Update Dashboard stocks field if open
                    Dashboard.updateStocksField();
                } catch(NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Invalid quantity. Enter a number.");
                }
            }

            private void updateProductDisplay(JTextArea taProducts) {
 StringBuilder sb = new StringBuilder();
        for(ProductItem p : productList) {
            sb.append("Name: ").append(p.name).append(", Quantity: ").append(p.quantity).append("\n");
        }
        taProducts.setText(sb.toString());
                }
        });

        JPanel panel = new JPanel();
        panel.add(lblName);
        panel.add(txtName);
        panel.add(lblQuantity);
        panel.add(txtQuantity);
        panel.add(btnAdd);
        panel.add(scrollPane);

        getContentPane().add(panel);

        pack();
        setLocationRelativeTo(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ADDPRODUCT = new javax.swing.JButton();
        REMOVEPRODUCT = new javax.swing.JButton();
        PRODUCTNAME = new javax.swing.JTextField();
        QUANTITY = new javax.swing.JTextField();
        PRICE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        STOCKTABLE = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        VIEWPRODUCTSONDATABASE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BACK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        ADDPRODUCT.setText("ADD PRODUCT");
        ADDPRODUCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDPRODUCTActionPerformed(evt);
            }
        });

        REMOVEPRODUCT.setText("REMOVE PRODUCT");
        REMOVEPRODUCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REMOVEPRODUCTActionPerformed(evt);
            }
        });

        PRODUCTNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRODUCTNAMEActionPerformed(evt);
            }
        });

        QUANTITY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QUANTITYActionPerformed(evt);
            }
        });

        PRICE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRICEActionPerformed(evt);
            }
        });

        STOCKTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "QUANTITY", "PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(STOCKTABLE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("ADD PRODUCT ");

        VIEWPRODUCTSONDATABASE.setText("VIEW PRODUCTS");

        jLabel2.setText("PRODUCT NAME");

        jLabel3.setText("QUANTITY");

        jLabel4.setText("PRICE");

        BACK.setText("BACK");
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QUANTITY, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PRICE, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PRODUCTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(ADDPRODUCT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(REMOVEPRODUCT)
                        .addGap(116, 116, 116)
                        .addComponent(VIEWPRODUCTSONDATABASE)
                        .addGap(28, 28, 28))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BACK)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BACK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VIEWPRODUCTSONDATABASE)
                            .addComponent(REMOVEPRODUCT))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PRODUCTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QUANTITY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PRICE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ADDPRODUCT)
                        .addGap(107, 107, 107))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PRODUCTNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRODUCTNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRODUCTNAMEActionPerformed

    private void QUANTITYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QUANTITYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QUANTITYActionPerformed

    private void PRICEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRICEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRICEActionPerformed

    private void ADDPRODUCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDPRODUCTActionPerformed
       addProductToTable();   
        // You can add validation and then update the table or database   
    }//GEN-LAST:event_ADDPRODUCTActionPerformed

    private void REMOVEPRODUCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REMOVEPRODUCTActionPerformed
        // TODO add your handling code here:
          removeSelectedProduct();
    }//GEN-LAST:event_REMOVEPRODUCTActionPerformed

    private void BACKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseClicked
        // TODO add your handling code here:
         new Dashboard().setVisible(true); 
    }//GEN-LAST:event_BACKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
              new Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDPRODUCT;
    private javax.swing.JButton BACK;
    private javax.swing.JTextField PRICE;
    private javax.swing.JTextField PRODUCTNAME;
    private javax.swing.JTextField QUANTITY;
    private javax.swing.JButton REMOVEPRODUCT;
    private javax.swing.JTable STOCKTABLE;
    private javax.swing.JButton VIEWPRODUCTSONDATABASE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void removeSelectedProduct() {
    int selectedRow = STOCKTABLE.getSelectedRow();

    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a product to remove.", "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
    } else {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) STOCKTABLE.getModel();
        model.removeRow(selectedRow);
    }    }

    private void addProductToTable() {
  String name = PRODUCTNAME.getText().trim();
    String qty = QUANTITY.getText().trim();
    String price = PRICE.getText().trim();

    if (name.isEmpty() || qty.isEmpty() || price.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "All fields must be filled out.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        int quantity = Integer.parseInt(qty);
        double unitPrice = Double.parseDouble(price);

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) STOCKTABLE.getModel();
        model.addRow(new Object[]{name, quantity, unitPrice});

        // Clear input fields after adding
        PRODUCTNAME.setText("");
        QUANTITY.setText("");
        PRICE.setText("");

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Quantity must be an integer and price must be a number.", "Format Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }    }
   public boolean reduceStock(String productName, int amount) {
    DefaultTableModel model = (DefaultTableModel) STOCKTABLE.getModel();
    for (int i = 0; i < model.getRowCount(); i++) {
        if (model.getValueAt(i, 0).toString().equalsIgnoreCase(productName)) {
            int currentQty = Integer.parseInt(model.getValueAt(i, 1).toString());
            if (currentQty >= amount) {
                model.setValueAt(currentQty - amount, i, 1);
                return true; // success
            } else {
                return false; // not enough stock
            }
        }
    }
    return false; // product not found
}
 public int getTotalQuantity() {
    DefaultTableModel model = (DefaultTableModel) STOCKTABLE.getModel();
    int totalQty = 0;
    for (int i = 0; i < model.getRowCount(); i++) {
        int qty = Integer.parseInt(model.getValueAt(i, 1).toString());
        totalQty += qty;
    }
    return totalQty;
}
}
